name: Publish Docker
run-name: ${{ github.actor }} is publishing azcopy to Docker Hub
on: 
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu -latest
    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: mcad7/azcopy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest, ${{ env.RELEASE_VERSION }}"
        workdir: 10/alpine
